### ISSUE TITLE
Setting `ATMOS_CLI_CONFIG_PATH` to a file path and not a directory path causes a panic

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/atmos#191]
## Describe the Bug
We set `ATMOS_CLI_CONFIG_PATH` to `/mnt/workspace/source/rootfs/usr/local/etc/atmos/atmos.yaml` and it resulted in the following: 

```
+ echo 'Writing Stack variables to spacelift.auto.tfvars.json for Spacelift...'
Writing Stack variables to spacelift.auto.tfvars.json for Spacelift...
+ atmos terraform write varfile app --stack=dev -f spacelift.auto.tfvars.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6a455c]

goroutine 1 [running]:
github.com/cloudposse/atmos/pkg/utils.FileExists({0xc0001609b0?, 0x46?})
	/home/runner/work/atmos/atmos/pkg/utils/file_utils.go:25 +0x5c
github.com/cloudposse/atmos/pkg/config.processConfigFile({0xc0001609b0, 0x46}, 0xc00035fc58?)
	/home/runner/work/atmos/atmos/pkg/config/config.go:363 +0x5a
github.com/cloudposse/atmos/pkg/config.InitConfig()
	/home/runner/work/atmos/atmos/pkg/config/config.go:158 +0x495
github.com/cloudposse/atmos/cmd.init.10()
	/home/runner/work/atmos/atmos/cmd/root.go:28 +0x10b
[01GBT2BASCMAXHJQZANQ61C2KF] Unexpected exit code when initializing workspace: 2
```

## Expected Behavior

We would expect a graceful failure instead of a panic. 

## Steps to Reproduce
1. Set `ATMOS_CLI_CONFIG_PATH` to a direct path to the `atmos.yaml` file instead of a directory. 
2. Execute a `atmos terraform plan` 
3. See error.

## Screenshots
N/A

## Environment (please complete the following information):

* Atmos version: v1.4.26

## Additional Context
 
cc @joe-niland

**Comment by aknysh** [comment]
@Gowiem thanks.
It's a path to atmos.yaml, should not include the file name

**Comment by nitrocode** [comment]
@Gowiem so try changing

```shell
export ATMOS_CLI_CONFIG_PATH=/mnt/workspace/source/rootfs/usr/local/etc/atmos/atmos.yaml
```

to

```shell
export ATMOS_CLI_CONFIG_PATH=/mnt/workspace/source/rootfs/usr/local/etc/atmos/
```

**Comment by Gowiem** [comment]
@aknysh @nitrocode yeah, we figured that out quickly and resolved the problem. 

I'm raising this issue because it shouldn't cause a panic and segfault with the above stacktrace -- We should instead get a nice error saying something along the following: 

> `atmos.yaml` was not found at the given path: `/mnt/workspace/source/rootfs/usr/local/etc/atmos/atmos.yamlatmos.yaml`. Please update your `ATMOS_CLI_CONFIG_PATH` to the correct directory where `atmos.yaml` can be found


That's all 😄

**Comment by aknysh** [comment]
> @aknysh @nitrocode yeah, we figured that out quickly and resolved the problem.
> 
> I'm raising this issue because it shouldn't cause a panic and segfault with the above stacktrace -- We should instead get a nice error saying something along the following:
> 
> > `atmos.yaml` was not found at the given path: `/mnt/workspace/source/rootfs/usr/local/etc/atmos/atmos.yamlatmos.yaml`. Please update your `ATMOS_CLI_CONFIG_PATH` to the correct directory where `atmos.yaml` can be found
> 
> That's all 😄

thank you @Gowiem , we'll improve it
